=== Mikk155/unity/src/data/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties":
    {
        "$schema":
        {
            "type": "string"
        },
        "Class":
        {
            "type": "string",
            "enum":
            [
                "Solid",
                "Point",
                "Base"
            ],
            "description": "Class type, in the FGD this is what goes in @{var}Class"
        },
        "size":
        {
            "type": "array",
            "description": "Size of a Point Entity",
            "items":
            {
                "type": "array",
                "items":
                {
                    "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
            },
            "minItems": 2,
            "maxItems": 2
        },
        "color":
        {
            "type": "array",
            "description": "Color of a Point Entity",
            "items":
            {
                "type": "integer"
            },
            "minItems": 3,
            "maxItems": 3
        },
        "studio":
        {
            "oneOf":
            [
                {
                    "type": "string"
                },
                {
                    "type": "boolean"
                }
            ],
            "description": "Studio model"
        },
        "sprite":
        {
            "oneOf":
            [
                {
                    "type": "string"
                },
                {
                    "type": "boolean"
                }
            ],
            "description": "Sprite model"
        },
        "iconsprite":
        {
            "type": "string",
            "description": "Sprite model (editor)"
        },
        "base":
        {
            "type": "array",
            "description": "Base classes for this Class",
            "items":
            {
                "type": "string"
            }
        },
        "title":
        {
            "type": "string",
            "description": "Short description referenced in ``docs/src/sentences.json``"
        },
        "description":
        {
            "type": "string",
            "description": "Long description referenced in ``docs/src/sentences.json``"
        },
        "data":
        {
            "type": "object",
            "patternProperties":
            {
                "^[a-zA-Z0-9_-]+$":
                {
                    "type": "object",
                    "properties":
                    {
                        "variable":
                        {
                            "type": "string",
                            "enum":
                            [
                                "string",
                                "integer",
                                "float",
                                "choices",
                                "target_destination",
                                "target_source",
                                "target_generic",
                                "angle",
                                "color255",
                                "color1",
                                "sound",
                                "sprite",
                                "studio",

                                "decal",

                                "vector",
                                "target_name_or_class",
                                "sky",
                                "scale"
                            ],
                            "description": "KeyValue variable type"
                        },
                        "title":
                        {
                            "type": "string",
                            "description": "Short description referenced in ``docs/src/sentences.json``"
                        },
                        "description":
                        {
                            "type": "string",
                            "description": "Long description referenced in ``docs/src/sentences.json``"
                        },
                        "value":
                        {
                            "oneOf":
                            [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                }
                            ],
                            "description": "Default value"
                        },
                        "choices":
                        {
                            "type": "object",
                            "patternProperties":
                            {
                                "^[a-zA-Z0-9_-]+$":
                                {
                                    "type": "object",
                                    "properties":
                                    {
                                        "title":
                                        {
                                            "type": "string",
                                            "description": "Short description referenced in ``docs/src/sentences.json``"
                                        },
                                        "description":
                                        {
                                            "type": "string",
                                            "description": "Long description referenced in ``docs/src/sentences.json``"
                                        }
                                    },
                                    "required": [ "title" ],
                                    "additionalProperties": false
                                }
                            },
                            "description": "Choices if variable is \"choices\"",
                            "additionalProperties": false
                        }
                    },
                    "required": [ "variable", "title" ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "required":
    [
        "$schema",
        "Class"
    ],
    "additionalProperties": false
}

=== Mikk155/unity/src/data/entities/monster_pitworm_up.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Monster",
        "Target",
        "RenderFields",
        "Angles",
        "CustomModel",
        "Unkillable",
        "Sequence"
    ],
    "studio": "models/pit_worm_up.mdl",
    "data": {},
    "title": "monster_pitworm_up::classname",
    "description": "monster_pitworm_up::classname::description"
}

=== Mikk155/unity/src/data/entities/trigger_entity_iterator.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "size": [
        [
            -12,
            -12,
            -12
        ],
        [
            12,
            12,
            12
        ]
    ],
    "color": [
        255,
        255,
        0
    ],
    "data": {
        "name_filter": {
            "variable": "target_destination",
            "value": "",
            "title": "trigger_entity_iterator::name_filter",
            "description": "trigger_entity_iterator::name_filter::description"
        },
        "classname_filter": {
            "variable": "string",
            "value": "",
            "title": "trigger_entity_iterator::classname_filter",
            "description": "trigger_entity_iterator::classname_filter::description"
        },
        "status_filter": {
            "variable": "choices",
            "value": "0",
            "choices": {
                "0": {
                    "title": "trigger_entity_iterator::status_filter::0",
                    "description": "trigger_entity_iterator::status_filter::0::description"
                },
                "1": {
                    "title": "trigger_entity_iterator::status_filter::1",
                    "description": "trigger_entity_iterator::status_filter::1::description"
                },
                "2": {
                    "title": "trigger_entity_iterator::status_filter::2",
                    "description": "trigger_entity_iterator::status_filter::2::description"
                }
            },
            "title": "trigger_entity_iterator::status_filter",
            "description": "trigger_entity_iterator::status_filter::description"
        },
        "delay_between_triggers": {
            "variable": "float",
            "value": "0.0",
            "title": "trigger_entity_iterator::delay_between_triggers",
            "description": "trigger_entity_iterator::delay_between_triggers::description"
        },
        "target": {
            "variable": "target_destination",
            "value": "",
            "title": "trigger_entity_iterator::target",
            "description": "trigger_entity_iterator::target::description"
        },
        "triggerstate": {
            "variable": "choices",
            "value": "0",
            "choices": {
                "0": {
                    "title": "trigger_entity_iterator::triggerstate::0",
                    "description": "trigger_entity_iterator::triggerstate::0::description"
                },
                "1": {
                    "title": "trigger_entity_iterator::triggerstate::1",
                    "description": "trigger_entity_iterator::triggerstate::1::description"
                },
                "2": {
                    "title": "trigger_entity_iterator::triggerstate::2",
                    "description": "trigger_entity_iterator::triggerstate::2::description"
                }
            },
            "title": "trigger_entity_iterator::triggerstate",
            "description": "trigger_entity_iterator::triggerstate::description"
        },
        "run_mode": {
            "variable": "choices",
            "value": "0",
            "choices": {
                "0": {
                    "title": "trigger_entity_iterator::run_mode::0",
                    "description": "trigger_entity_iterator::run_mode::0::description"
                },
                "1": {
                    "title": "trigger_entity_iterator::run_mode::1",
                    "description": "trigger_entity_iterator::run_mode::1::description"
                },
                "2": {
                    "title": "trigger_entity_iterator::run_mode::2",
                    "description": "trigger_entity_iterator::run_mode::2::description"
                }
            },
            "title": "trigger_entity_iterator::run_mode",
            "description": "trigger_entity_iterator::run_mode::description"
        },
        "trigger_after_run": {
            "variable": "target_destination",
            "value": "",
            "title": "trigger_entity_iterator::trigger_after_run",
            "description": "trigger_entity_iterator::trigger_after_run::description"
        },
        "maximum_runs": {
            "variable": "integer",
            "value": "0",
            "title": "trigger_entity_iterator::maximum_runs",
            "description": "trigger_entity_iterator::maximum_runs::description"
        },
        "delay_between_runs": {
            "variable": "float",
            "value": "0.5",
            "title": "trigger_entity_iterator::delay_between_runs",
            "description": "trigger_entity_iterator::delay_between_runs::description"
        }
    },
    "title": "trigger_entity_iterator::classname",
    "description": "trigger_entity_iterator::classname::description"
}

=== Mikk155/unity/src/data/entities/func_plat.json
{
	"$schema": "../schema.json",
    "Class": "Solid",
    "base": [
        "Global",
        "RenderFields",
        "PlatSounds",
        "minlight",
        "ZHLT"
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "func_plat::spawnflags::1",
                    "description": "func_plat::spawnflags::1::description"
                }
            }
        },
        "height": {
            "variable": "integer",
            "value": "0",
            "title": "func_plat::height",
            "description": "func_plat::height::description"
        },
        "speed": {
            "variable": "integer",
            "value": "50",
            "title": "func_plat::speed",
            "description": "func_plat::speed::description"
        }
    },
    "title": "func_plat::classname",
    "description": "func_plat::classname::description"
}

=== Mikk155/unity/src/data/entities/xen_hair.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "RenderFields",
        "Angles"
    ],
    "studio": "models/hair.mdl",
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "xen_hair::spawnflags::1",
                    "description": "xen_hair::spawnflags::1::description"
                }
            }
        }
    },
    "title": "xen_hair::classname",
    "description": "xen_hair::classname::description"
}

=== Mikk155/unity/src/data/entities/ammo_crossbow.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Target",
        "CBaseDelay",
        "Angles",
        "RenderFields",
        "Ammo"
    ],
    "studio": true,
    "data": {
        "model": {
            "variable": "studio",
            "value": "models/w_crossbow_clip.mdl",
            "title": "CustomKeys::model"
        }
    },
    "title": "ammo_crossbow::classname",
    "description": "ammo_crossbow::classname::description"
}

=== Mikk155/unity/src/data/entities/func_breakable.json
{
	"$schema": "../schema.json",
    "Class": "Solid",
    "base": [
        "Breakable",
        "RenderFields",
        "Angles",
        "ZHLT",
        "minlight"
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "func_breakable::spawnflags::1",
                    "description": "func_breakable::spawnflags::1::description"
                },
                "2": {
                    "title": "func_breakable::spawnflags::2",
                    "description": "func_breakable::spawnflags::2::description"
                },
                "4": {
                    "title": "func_breakable::spawnflags::4",
                    "description": "func_breakable::spawnflags::4::description"
                },
                "256": {
                    "title": "func_breakable::spawnflags::256",
                    "description": "func_breakable::spawnflags::256::description"
                }
            }
        }
    },
    "title": "func_breakable::classname",
    "description": "func_breakable::classname::description"
}

=== Mikk155/unity/src/data/entities/monster_male_assassin.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Monster",
        "Target",
        "RenderFields",
        "Angles",
        "CustomModel",
        "Unkillable",
        "Sequence"
    ],
    "studio": "models/massn.mdl",
    "data": {
        "netname": {
            "variable": "string",
            "value": "",
            "title": "monster_male_assassin::netname",
            "description": "monster_male_assassin::netname::description"
        },
        "spawnflags": {
            "choices": {
                "32": {
                    "title": "monster_male_assassin::spawnflags::32",
                    "description": "monster_male_assassin::spawnflags::32::description"
                }
            }
        },
        "head": {
            "variable": "choices",
            "value": "0",
            "choices": {
                "-1": {
                    "title": "monster_male_assassin::head::-1",
                    "description": "monster_male_assassin::head::-1::description"
                },
                "0": {
                    "title": "monster_male_assassin::head::0",
                    "description": "monster_male_assassin::head::0::description"
                },
                "1": {
                    "title": "monster_male_assassin::head::1",
                    "description": "monster_male_assassin::head::1::description"
                },
                "2": {
                    "title": "monster_male_assassin::head::2",
                    "description": "monster_male_assassin::head::2::description"
                }
            },
            "title": "monster_male_assassin::head",
            "description": "monster_male_assassin::head::description"
        },
        "weapons": {
            "variable": "choices",
            "value": "3",
            "choices": {
                "0": {
                    "title": "monster_male_assassin::weapons::0",
                    "description": "monster_male_assassin::weapons::0::description"
                },
                "1": {
                    "title": "monster_male_assassin::weapons::1",
                    "description": "monster_male_assassin::weapons::1::description"
                },
                "3": {
                    "title": "monster_male_assassin::weapons::3",
                    "description": "monster_male_assassin::weapons::3::description"
                },
                "5": {
                    "title": "monster_male_assassin::weapons::5",
                    "description": "monster_male_assassin::weapons::5::description"
                },
                "8": {
                    "title": "monster_male_assassin::weapons::8",
                    "description": "monster_male_assassin::weapons::8::description"
                }
            },
            "title": "monster_male_assassin::weapons",
            "description": "monster_male_assassin::weapons::description"
        },
        "standgroundrange": {
            "variable": "string",
            "value": "0.0",
            "title": "monster_male_assassin::standgroundrange",
            "description": "monster_male_assassin::standgroundrange::description"
        }
    },
    "title": "monster_male_assassin::classname",
    "description": "monster_male_assassin::classname::description"
}

=== Mikk155/unity/src/data/entities/func_platrot.json
{
	"$schema": "../schema.json",
    "Class": "Solid",
    "base": [
        "Global",
        "RenderFields",
        "PlatSounds",
        "Angles",
        "minlight",
        "ZHLT"
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "func_platrot::spawnflags::1",
                    "description": "func_platrot::spawnflags::1::description"
                },
                "64": {
                    "title": "func_platrot::spawnflags::64",
                    "description": "func_platrot::spawnflags::64::description"
                },
                "128": {
                    "title": "func_platrot::spawnflags::128",
                    "description": "func_platrot::spawnflags::128::description"
                }
            }
        },
        "speed": {
            "variable": "integer",
            "value": "50",
            "title": "func_platrot::speed",
            "description": "func_platrot::speed::description"
        },
        "height": {
            "variable": "integer",
            "value": "0",
            "title": "func_platrot::height",
            "description": "func_platrot::height::description"
        },
        "rotation": {
            "variable": "integer",
            "value": "0",
            "title": "func_platrot::rotation",
            "description": "func_platrot::rotation::description"
        }
    },
    "title": "func_platrot::classname",
    "description": "func_platrot::classname::description"
}
