=== Mikk155/unity/src/data/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties":
    {
        "$schema":
        {
            "type": "string"
        },
        "Class":
        {
            "type": "string",
            "enum":
            [
                "Solid",
                "Point",
                "Base"
            ],
            "description": "Class type, in the FGD this is what goes in @{var}Class"
        },
        "size":
        {
            "type": "array",
            "description": "Size of a Point Entity",
            "items":
            {
                "type": "array",
                "items":
                {
                    "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
            },
            "minItems": 2,
            "maxItems": 2
        },
        "color":
        {
            "type": "array",
            "description": "Color of a Point Entity",
            "items":
            {
                "type": "integer"
            },
            "minItems": 3,
            "maxItems": 3
        },
        "studio":
        {
            "oneOf":
            [
                {
                    "type": "string"
                },
                {
                    "type": "boolean"
                }
            ],
            "description": "Studio model"
        },
        "sprite":
        {
            "oneOf":
            [
                {
                    "type": "string"
                },
                {
                    "type": "boolean"
                }
            ],
            "description": "Sprite model"
        },
        "iconsprite":
        {
            "type": "string",
            "description": "Sprite model (editor)"
        },
        "base":
        {
            "type": "array",
            "description": "Base classes for this Class",
            "items":
            {
                "type": "string"
            }
        },
        "title":
        {
            "type": "string",
            "description": "Short description referenced in ``docs/src/sentences.json``"
        },
        "description":
        {
            "type": "string",
            "description": "Long description referenced in ``docs/src/sentences.json``"
        },
        "data":
        {
            "type": "object",
            "patternProperties":
            {
                "^[a-zA-Z0-9_-]+$":
                {
                    "type": "object",
                    "properties":
                    {
                        "variable":
                        {
                            "type": "string",
                            "enum":
                            [
                                "string",
                                "integer",
                                "float",
                                "choices",
                                "target_destination",
                                "target_source",
                                "target_generic",
                                "angle",
                                "color255",
                                "color1",
                                "sound",
                                "sprite",
                                "studio",

                                "decal",

                                "vector",
                                "target_name_or_class",
                                "sky",
                                "scale"
                            ],
                            "description": "KeyValue variable type"
                        },
                        "title":
                        {
                            "type": "string",
                            "description": "Short description referenced in ``docs/src/sentences.json``"
                        },
                        "description":
                        {
                            "type": "string",
                            "description": "Long description referenced in ``docs/src/sentences.json``"
                        },
                        "value":
                        {
                            "oneOf":
                            [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                }
                            ],
                            "description": "Default value"
                        },
                        "choices":
                        {
                            "type": "object",
                            "patternProperties":
                            {
                                "^[a-zA-Z0-9_-]+$":
                                {
                                    "type": "object",
                                    "properties":
                                    {
                                        "title":
                                        {
                                            "type": "string",
                                            "description": "Short description referenced in ``docs/src/sentences.json``"
                                        },
                                        "description":
                                        {
                                            "type": "string",
                                            "description": "Long description referenced in ``docs/src/sentences.json``"
                                        }
                                    },
                                    "required": [ "title" ],
                                    "additionalProperties": false
                                }
                            },
                            "description": "Choices if variable is \"choices\"",
                            "additionalProperties": false
                        }
                    },
                    "required": [ "variable", "title" ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "required":
    [
        "$schema",
        "Class"
    ],
    "additionalProperties": false
}

=== Mikk155/unity/src/data/entities/path_track.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "size": [
        [
            16,
            16,
            16
        ]
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "path_track::spawnflags::1",
                    "description": "path_track::spawnflags::1::description"
                },
                "2": {
                    "title": "path_track::spawnflags::2",
                    "description": "path_track::spawnflags::2::description"
                },
                "4": {
                    "title": "path_track::spawnflags::4",
                    "description": "path_track::spawnflags::4::description"
                },
                "8": {
                    "title": "path_track::spawnflags::8",
                    "description": "path_track::spawnflags::8::description"
                }
            }
        },
        "target": {
            "variable": "target_destination",
            "title": "path_track::target",
            "description": "path_track::target::description"
        },
        "message": {
            "variable": "target_destination",
            "title": "path_track::message",
            "description": "path_track::message::description"
        },
        "altpath": {
            "variable": "target_destination",
            "title": "path_track::altpath",
            "description": "path_track::altpath::description"
        },
        "netname": {
            "variable": "target_destination",
            "title": "path_track::netname",
            "description": "path_track::netname::description"
        },
        "speed": {
            "variable": "integer",
            "value": "0",
            "title": "path_track::speed",
            "description": "path_track::speed::description"
        }
    },
    "title": "path_track::classname",
    "description": "path_track::classname::description"
}

=== Mikk155/unity/src/data/entities/env_render.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Target",
        "RenderFields"
    ],
    "size": [
        [
            -16,
            -16,
            -16
        ],
        [
            16,
            16,
            16
        ]
    ],
    "color": [
        100,
        100,
        0
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "env_render::spawnflags::1",
                    "description": "env_render::spawnflags::1::description"
                },
                "2": {
                    "title": "env_render::spawnflags::2",
                    "description": "env_render::spawnflags::2::description"
                },
                "4": {
                    "title": "env_render::spawnflags::4",
                    "description": "env_render::spawnflags::4::description"
                },
                "8": {
                    "title": "env_render::spawnflags::8",
                    "description": "env_render::spawnflags::8::description"
                }
            }
        }
    },
    "title": "env_render::classname",
    "description": "env_render::classname::description"
}

=== Mikk155/unity/src/data/entities/ammo_gaussclip.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Target",
        "CBaseDelay",
        "Angles",
        "RenderFields",
        "Ammo"
    ],
    "studio": true,
    "data": {
        "model": {
            "variable": "studio",
            "value": "models/w_gaussammo.mdl",
            "title": "CustomKeys::model"
        }
    },
    "title": "ammo_gaussclip::classname",
    "description": "ammo_gaussclip::classname::description"
}

=== Mikk155/unity/src/data/entities/monster_cleansuit_scientist_dead.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "RenderFields",
        "Sequence"
    ],
    "studio": "models/cleansuit_scientist.mdl",
    "data": {
        "body": {
            "variable": "choices",
            "value": "-1",
            "choices": {
                "-1": {
                    "title": "monster_cleansuit_scientist_dead::body::-1",
                    "description": "monster_cleansuit_scientist_dead::body::-1::description"
                },
                "0": {
                    "title": "monster_cleansuit_scientist_dead::body::0",
                    "description": "monster_cleansuit_scientist_dead::body::0::description"
                },
                "1": {
                    "title": "monster_cleansuit_scientist_dead::body::1",
                    "description": "monster_cleansuit_scientist_dead::body::1::description"
                },
                "2": {
                    "title": "monster_cleansuit_scientist_dead::body::2",
                    "description": "monster_cleansuit_scientist_dead::body::2::description"
                },
                "3": {
                    "title": "monster_cleansuit_scientist_dead::body::3",
                    "description": "monster_cleansuit_scientist_dead::body::3::description"
                }
            },
            "title": "monster_cleansuit_scientist_dead::body",
            "description": "monster_cleansuit_scientist_dead::body::description"
        },
        "pose": {
            "variable": "choices",
            "value": "0",
            "choices": {
                "0": {
                    "title": "monster_cleansuit_scientist_dead::pose::0",
                    "description": "monster_cleansuit_scientist_dead::pose::0::description"
                },
                "1": {
                    "title": "monster_cleansuit_scientist_dead::pose::1",
                    "description": "monster_cleansuit_scientist_dead::pose::1::description"
                },
                "2": {
                    "title": "monster_cleansuit_scientist_dead::pose::2",
                    "description": "monster_cleansuit_scientist_dead::pose::2::description"
                },
                "3": {
                    "title": "monster_cleansuit_scientist_dead::pose::3",
                    "description": "monster_cleansuit_scientist_dead::pose::3::description"
                },
                "4": {
                    "title": "monster_cleansuit_scientist_dead::pose::4",
                    "description": "monster_cleansuit_scientist_dead::pose::4::description"
                },
                "5": {
                    "title": "monster_cleansuit_scientist_dead::pose::5",
                    "description": "monster_cleansuit_scientist_dead::pose::5::description"
                },
                "6": {
                    "title": "monster_cleansuit_scientist_dead::pose::6",
                    "description": "monster_cleansuit_scientist_dead::pose::6::description"
                },
                "7": {
                    "title": "monster_cleansuit_scientist_dead::pose::7",
                    "description": "monster_cleansuit_scientist_dead::pose::7::description"
                },
                "8": {
                    "title": "monster_cleansuit_scientist_dead::pose::8",
                    "description": "monster_cleansuit_scientist_dead::pose::8::description"
                }
            },
            "title": "monster_cleansuit_scientist_dead::pose",
            "description": "monster_cleansuit_scientist_dead::pose::description"
        }
    },
    "title": "monster_cleansuit_scientist_dead::classname",
    "description": "monster_cleansuit_scientist_dead::classname::description"
}

=== Mikk155/unity/src/data/entities/game_player_team.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Master"
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "game_player_team::spawnflags::1",
                    "description": "game_player_team::spawnflags::1::description"
                },
                "2": {
                    "title": "game_player_team::spawnflags::2",
                    "description": "game_player_team::spawnflags::2::description"
                },
                "4": {
                    "title": "game_player_team::spawnflags::4",
                    "description": "game_player_team::spawnflags::4::description"
                }
            }
        },
        "target": {
            "variable": "string",
            "value": "",
            "title": "game_player_team::target",
            "description": "game_player_team::target::description"
        }
    },
    "title": "game_player_team::classname",
    "description": "game_player_team::classname::description"
}

=== Mikk155/unity/src/data/entities/monster_apache.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Monster",
        "Target",
        "RenderFields",
        "Angles",
        "CustomModel",
        "Unkillable",
        "Sequence",
        "SF64_StartInactive"
    ],
    "size": [
        [
            -360,
            -360,
            -172
        ],
        [
            360,
            360,
            8
        ]
    ],
    "studio": "models/apache.mdl",
    "data": {
        "spawnflags": {
            "choices": {
                "8": {
                    "title": "monster_apache::spawnflags::8",
                    "description": "monster_apache::spawnflags::8::description"
                }
            }
        }
    },
    "title": "monster_apache::classname",
    "description": "monster_apache::classname::description"
}

=== Mikk155/unity/src/data/entities/game_score.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Master"
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "game_score::spawnflags::1",
                    "description": "game_score::spawnflags::1::description"
                },
                "2": {
                    "title": "game_score::spawnflags::2",
                    "description": "game_score::spawnflags::2::description"
                }
            }
        },
        "points": {
            "variable": "integer",
            "value": "1",
            "title": "game_score::points",
            "description": "game_score::points::description"
        }
    },
    "title": "game_score::classname",
    "description": "game_score::classname::description"
}

=== Mikk155/unity/src/data/entities/weapon_displacer.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Target",
        "CBaseDelay",
        "RenderFields",
        "Weapon"
    ],
    "studio": "models/w_displacer.mdl",
    "data": {},
    "title": "weapon_displacer::classname",
    "description": "weapon_displacer::classname::description"
}
