=== Mikk155/unity/src/data/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties":
    {
        "$schema":
        {
            "type": "string"
        },
        "Class":
        {
            "type": "string",
            "enum":
            [
                "Solid",
                "Point",
                "Base"
            ],
            "description": "Class type, in the FGD this is what goes in @{var}Class"
        },
        "size":
        {
            "type": "array",
            "description": "Size of a Point Entity",
            "items":
            {
                "type": "array",
                "items":
                {
                    "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
            },
            "minItems": 2,
            "maxItems": 2
        },
        "color":
        {
            "type": "array",
            "description": "Color of a Point Entity",
            "items":
            {
                "type": "integer"
            },
            "minItems": 3,
            "maxItems": 3
        },
        "studio":
        {
            "oneOf":
            [
                {
                    "type": "string"
                },
                {
                    "type": "boolean"
                }
            ],
            "description": "Studio model"
        },
        "sprite":
        {
            "oneOf":
            [
                {
                    "type": "string"
                },
                {
                    "type": "boolean"
                }
            ],
            "description": "Sprite model"
        },
        "iconsprite":
        {
            "type": "string",
            "description": "Sprite model (editor)"
        },
        "base":
        {
            "type": "array",
            "description": "Base classes for this Class",
            "items":
            {
                "type": "string"
            }
        },
        "title":
        {
            "type": "string",
            "description": "Short description referenced in ``docs/src/sentences.json``"
        },
        "description":
        {
            "type": "string",
            "description": "Long description referenced in ``docs/src/sentences.json``"
        },
        "data":
        {
            "type": "object",
            "patternProperties":
            {
                "^[a-zA-Z0-9_-]+$":
                {
                    "type": "object",
                    "properties":
                    {
                        "variable":
                        {
                            "type": "string",
                            "enum":
                            [
                                "string",
                                "integer",
                                "float",
                                "choices",
                                "target_destination",
                                "target_source",
                                "target_generic",
                                "angle",
                                "color255",
                                "color1",
                                "sound",
                                "sprite",
                                "studio",

                                "decal",

                                "vector",
                                "target_name_or_class",
                                "sky",
                                "scale"
                            ],
                            "description": "KeyValue variable type"
                        },
                        "title":
                        {
                            "type": "string",
                            "description": "Short description referenced in ``docs/src/sentences.json``"
                        },
                        "description":
                        {
                            "type": "string",
                            "description": "Long description referenced in ``docs/src/sentences.json``"
                        },
                        "value":
                        {
                            "oneOf":
                            [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                }
                            ],
                            "description": "Default value"
                        },
                        "choices":
                        {
                            "type": "object",
                            "patternProperties":
                            {
                                "^[a-zA-Z0-9_-]+$":
                                {
                                    "type": "object",
                                    "properties":
                                    {
                                        "title":
                                        {
                                            "type": "string",
                                            "description": "Short description referenced in ``docs/src/sentences.json``"
                                        },
                                        "description":
                                        {
                                            "type": "string",
                                            "description": "Long description referenced in ``docs/src/sentences.json``"
                                        }
                                    },
                                    "required": [ "title" ],
                                    "additionalProperties": false
                                }
                            },
                            "description": "Choices if variable is \"choices\"",
                            "additionalProperties": false
                        }
                    },
                    "required": [ "variable", "title" ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "required":
    [
        "$schema",
        "Class"
    ],
    "additionalProperties": false
}

=== Mikk155/unity/src/data/entities/point_teleport.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Master",
        "Angles",
        "TeleportBase"
    ],
    "color": [
        0,
        255,
        0
    ],
    "data": {
        "target": {
            "variable": "target_destination",
            "value": "",
            "title": "point_teleport::target",
            "description": "point_teleport::target::description"
        }
    },
    "title": "point_teleport::classname",
    "description": "point_teleport::classname::description"
}

=== Mikk155/unity/src/data/entities/info_intermission.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Target",
        "Angles"
    ],
    "size": [
        [
            -4,
            -4,
            -4
        ],
        [
            4,
            4,
            4
        ]
    ],
    "color": [
        0,
        255,
        0
    ],
    "title": "info_intermission::classname",
    "description": "info_intermission::classname::description"
}

=== Mikk155/unity/src/data/entities/monster_human_grunt_ally_dead.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "RenderFields",
        "Sequence"
    ],
    "studio": "models/hgrunt_opfor.mdl",
    "data": {
        "pose": {
            "variable": "choices",
            "value": "0",
            "choices": {
                "0": {
                    "title": "monster_human_grunt_ally_dead::pose::0",
                    "description": "monster_human_grunt_ally_dead::pose::0::description"
                },
                "1": {
                    "title": "monster_human_grunt_ally_dead::pose::1",
                    "description": "monster_human_grunt_ally_dead::pose::1::description"
                },
                "2": {
                    "title": "monster_human_grunt_ally_dead::pose::2",
                    "description": "monster_human_grunt_ally_dead::pose::2::description"
                },
                "3": {
                    "title": "monster_human_grunt_ally_dead::pose::3",
                    "description": "monster_human_grunt_ally_dead::pose::3::description"
                },
                "4": {
                    "title": "monster_human_grunt_ally_dead::pose::4",
                    "description": "monster_human_grunt_ally_dead::pose::4::description"
                },
                "5": {
                    "title": "monster_human_grunt_ally_dead::pose::5",
                    "description": "monster_human_grunt_ally_dead::pose::5::description"
                },
                "6": {
                    "title": "monster_human_grunt_ally_dead::pose::6",
                    "description": "monster_human_grunt_ally_dead::pose::6::description"
                }
            },
            "title": "monster_human_grunt_ally_dead::pose",
            "description": "monster_human_grunt_ally_dead::pose::description"
        },
        "weapons": {
            "variable": "choices",
            "value": "1",
            "choices": {
                "0": {
                    "title": "monster_human_grunt_ally_dead::weapons::0",
                    "description": "monster_human_grunt_ally_dead::weapons::0::description"
                },
                "1": {
                    "title": "monster_human_grunt_ally_dead::weapons::1",
                    "description": "monster_human_grunt_ally_dead::weapons::1::description"
                },
                "8": {
                    "title": "monster_human_grunt_ally_dead::weapons::8",
                    "description": "monster_human_grunt_ally_dead::weapons::8::description"
                },
                "16": {
                    "title": "monster_human_grunt_ally_dead::weapons::16",
                    "description": "monster_human_grunt_ally_dead::weapons::16::description"
                }
            },
            "title": "monster_human_grunt_ally_dead::weapons",
            "description": "monster_human_grunt_ally_dead::weapons::description"
        },
        "head": {
            "variable": "choices",
            "value": "0",
            "choices": {
                "0": {
                    "title": "monster_human_grunt_ally_dead::head::0",
                    "description": "monster_human_grunt_ally_dead::head::0::description"
                },
                "1": {
                    "title": "monster_human_grunt_ally_dead::head::1",
                    "description": "monster_human_grunt_ally_dead::head::1::description"
                },
                "2": {
                    "title": "monster_human_grunt_ally_dead::head::2",
                    "description": "monster_human_grunt_ally_dead::head::2::description"
                },
                "3": {
                    "title": "monster_human_grunt_ally_dead::head::3",
                    "description": "monster_human_grunt_ally_dead::head::3::description"
                },
                "4": {
                    "title": "monster_human_grunt_ally_dead::head::4",
                    "description": "monster_human_grunt_ally_dead::head::4::description"
                },
                "5": {
                    "title": "monster_human_grunt_ally_dead::head::5",
                    "description": "monster_human_grunt_ally_dead::head::5::description"
                },
                "6": {
                    "title": "monster_human_grunt_ally_dead::head::6",
                    "description": "monster_human_grunt_ally_dead::head::6::description"
                },
                "7": {
                    "title": "monster_human_grunt_ally_dead::head::7",
                    "description": "monster_human_grunt_ally_dead::head::7::description"
                }
            },
            "title": "monster_human_grunt_ally_dead::head",
            "description": "monster_human_grunt_ally_dead::head::description"
        }
    },
    "title": "monster_human_grunt_ally_dead::classname",
    "description": "monster_human_grunt_ally_dead::classname::description"
}

=== Mikk155/unity/src/data/entities/func_door_momentary.json
{
	"$schema": "../schema.json",
    "Class": "Solid",
    "base": [
        "Door",
        "ZHLT"
    ],
    "data": {
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "func_door_momentary::spawnflags::1",
                    "description": "func_door_momentary::spawnflags::1::description"
                }
            }
        }
    },
    "title": "func_door_momentary::classname",
    "description": "func_door_momentary::classname::description"
}

=== Mikk155/unity/src/data/entities/func_rot_button.json
{
	"$schema": "../schema.json",
    "Class": "Solid",
    "base": [
        "Target",
        "Global",
        "Master",
        "RenderFields",
        "Angles",
        "minlight",
        "ZHLT",
        "ReplacementFiles"
    ],
    "data": {
        "changetarget": {
            "variable": "target_destination",
            "value": "",
            "title": "func_rot_button::changetarget",
            "description": "func_rot_button::changetarget::description"
        },
        "speed": {
            "variable": "integer",
            "value": "50",
            "title": "func_rot_button::speed",
            "description": "func_rot_button::speed::description"
        },
        "health": {
            "variable": "integer",
            "value": "",
            "title": "func_rot_button::health",
            "description": "func_rot_button::health::description"
        },
        "sounds": {
            "variable": "sound",
            "value": "buttons/level1.wav",
            "title": "func_rot_button::sounds",
            "description": "func_rot_button::sounds::description"
        },
        "wait": {
            "variable": "choices",
            "value": "3",
            "choices": {
                "-1": {
                    "title": "func_rot_button::wait::-1",
                    "description": "func_rot_button::wait::-1::description"
                }
            },
            "title": "func_rot_button::wait",
            "description": "func_rot_button::wait::description"
        },
        "delay": {
            "variable": "string",
            "value": "0",
            "title": "func_rot_button::delay",
            "description": "func_rot_button::delay::description"
        },
        "distance": {
            "variable": "integer",
            "value": "90",
            "title": "func_rot_button::distance",
            "description": "func_rot_button::distance::description"
        },
        "spawnflags": {
            "choices": {
                "1": {
                    "title": "func_rot_button::spawnflags::1",
                    "description": "func_rot_button::spawnflags::1::description"
                },
                "2": {
                    "title": "func_rot_button::spawnflags::2",
                    "description": "func_rot_button::spawnflags::2::description"
                },
                "32": {
                    "title": "func_rot_button::spawnflags::32",
                    "description": "func_rot_button::spawnflags::32::description"
                },
                "64": {
                    "title": "func_rot_button::spawnflags::64",
                    "description": "func_rot_button::spawnflags::64::description"
                },
                "128": {
                    "title": "func_rot_button::spawnflags::128",
                    "description": "func_rot_button::spawnflags::128::description"
                },
                "256": {
                    "title": "func_rot_button::spawnflags::256",
                    "description": "func_rot_button::spawnflags::256::description"
                }
            }
        }
    },
    "title": "func_rot_button::classname",
    "description": "func_rot_button::classname::description"
}

=== Mikk155/unity/src/data/entities/env_glow.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "scale",
        "RenderFields"
    ],
    "size": [
        [
            -4,
            -4,
            -4
        ],
        [
            4,
            4,
            4
        ]
    ],
    "color": [
        30,
        100,
        0
    ],
    "sprite": true,
    "data": {
        "model": {
            "variable": "sprite",
            "value": "sprites/glow01.spr",
            "title": "CustomKeys::sprite"
        }
    },
    "title": "env_glow::classname",
    "description": "env_glow::classname::description"
}

=== Mikk155/unity/src/data/entities/env_shooter.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Angles",
        "gibshooterbase",
        "scale",
        "RenderFields"
    ],
    "size": [
        [
            -16,
            -16,
            -16
        ],
        [
            16,
            16,
            16
        ]
    ],
    "data": {
        "shootmodel": {
            "variable": "studio",
            "title": "env_shooter::shootmodel",
            "description": "env_shooter::shootmodel::description"
        },
        "shootsounds": {
            "variable": "choices",
            "value": "-1",
            "choices": {
                "-1": {
                    "title": "env_shooter::shootsounds::-1",
                    "description": "env_shooter::shootsounds::-1::description"
                },
                "0": {
                    "title": "env_shooter::shootsounds::0",
                    "description": "env_shooter::shootsounds::0::description"
                },
                "1": {
                    "title": "env_shooter::shootsounds::1",
                    "description": "env_shooter::shootsounds::1::description"
                },
                "2": {
                    "title": "env_shooter::shootsounds::2",
                    "description": "env_shooter::shootsounds::2::description"
                },
                "3": {
                    "title": "env_shooter::shootsounds::3",
                    "description": "env_shooter::shootsounds::3::description"
                },
                "4": {
                    "title": "env_shooter::shootsounds::4",
                    "description": "env_shooter::shootsounds::4::description"
                }
            },
            "title": "env_shooter::shootsounds",
            "description": "env_shooter::shootsounds::description"
        },
        "skin": {
            "variable": "integer",
            "value": "0",
            "title": "env_shooter::skin",
            "description": "env_shooter::skin::description"
        }
    },
    "title": "env_shooter::classname",
    "description": "env_shooter::classname::description"
}

=== Mikk155/unity/src/data/entities/monster_flyer_flock.json
{
	"$schema": "../schema.json",
    "Class": "Point",
    "base": [
        "Monster",
        "Target",
        "RenderFields",
        "Angles",
        "CustomModel",
        "Unkillable",
        "Sequence"
    ],
    "size": [
        [
            -16,
            -16,
            0
        ],
        [
            16,
            16,
            16
        ]
    ],
    "studio": "models/aflock.mdl",
    "data": {
        "iFlockSize": {
            "variable": "integer",
            "value": "8",
            "title": "monster_flyer_flock::iFlockSize",
            "description": "monster_flyer_flock::iFlockSize::description"
        },
        "flFlockRadius": {
            "variable": "integer",
            "value": "128",
            "title": "monster_flyer_flock::flFlockRadius",
            "description": "monster_flyer_flock::flFlockRadius::description"
        }
    },
    "title": "monster_flyer_flock::classname",
    "description": "monster_flyer_flock::classname::description"
}
